local CoreGui = game:GetService("StarterGui")

CoreGui:SetCore("SendNotification", {
    Title = "å‡†å¤‡è„šæœ¬",
    Text = "æ­£åœ¨åŠ è½½ï¼ˆåæŒ‚æœºå·²å¼€å¯ï¼‰",
    Duration = 5, 
})
print("åæŒ‚æœºå¼€å¯")
		local vu = game:GetService("VirtualUser")
		game:GetService("Players").LocalPlayer.Idled:connect(function()
		   vu:Button2Down(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
		   wait(1)
		   vu:Button2Up(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
		end)
local OrionLib = loadstring(game:HttpGet("https://pastebin.com/raw/dUiCrXYP"))()
local Window = OrionLib:MakeWindow({Name = "å¡å¡å¤§è›‡è„šæœ¬", HidePremium = false, SaveConfig = true,IntroText = "æ¬¢è¿ä½¿ç”¨å¡å¡å¤§è›‡è„šæœ¬", ConfigFolder = "æ¬¢è¿ä½¿ç”¨å¡å¡å¤§è›‡è„šæœ¬"})
local about = Window:MakeTab({
    Name = "å¡å¡å¤§è›‡è„šæœ¬",
    Icon = "rbxassetid://93566402708060",
    PremiumOnly = false
})

about:AddParagraph("æ‚¨çš„ç”¨æˆ·å:"," "..game.Players.LocalPlayer.Name.."")
about:AddParagraph("æ‚¨çš„æ³¨å…¥å™¨:"," "..identifyexecutor().."")
about:AddParagraph("æ‚¨å½“å‰æœåŠ¡å™¨çš„ID"," "..game.GameId.."")

local Tab = Window:MakeTab({
	Name = "æœ‰è¯è¯´",
	Icon = "rbxassetid://93566402708060",
	PremiumOnly = false
})

local Tab = Window:MakeTab({
	Name = "è„šæœ¬",
	Icon = "rbxassetid://93566402708060",
	PremiumOnly = false
})

local Section = Tab:AddSection({
	Name = "åŠŸèƒ½"
})

Tab:AddButton({
	Name = "æ°´ä¸‹ä¸–ç•Œæ”¯æŒå¾ˆå¤šæ¸¸æˆ_åå•å·²è¢«ç ´é™¤",
	Callback = function()
loadstring(game:HttpGet(('https://raw.githubusercontent.com/jiankeQWQ/Fish/main/sx')))()
    end
})

Tab:AddButton({
    Name = "å¡å¡å¤§è›‡",
    Callback = function()
   jianke_V3 = "ä½œè€…_å¡å¡ = "æœ¬äººQQ2528932281"loadstring(game:HttpGet(('https://raw.githubusercontent.com/jiankeQWQ/jiankeV3/main/jianke_V3')))()
    end
})

local Tab = Window:MakeTab({
	Name = "ğŸ€é€šç”¨åŠŸèƒ½ğŸ€",
	Icon = "rbxassetid://93566402708060",
	PremiumOnly = false
})

Tab:AddButton({
	Name = "Synapse X",
	Callback = function()
     loadstring(game:HttpGet("https://pastebin.com/raw/tWGxhNq0"))()
  	end    
})

Tab:AddButton({
    Name = "å·åˆ«äººç‰©å“æ ",
    Callback = function()
          --Copy And Paste:
    for i,v in pairs (game.Players:GetChildren()) do
    wait()
    for i,b in pairs (v.Backpack:GetChildren()) do
    b.Parent = game.Players.LocalPlayer.       Backpack
    end
    end
      end
})

Tab:AddButton({
	Name = "ä¼ªåè¯´è¯",
	Callback = function()
loadstring(game:HttpGet(('https://pastefy.ga/zCFEwaYq/raw'),true))()
	end 
})

Tab:AddButton({
  Name = "HUA å…‰å½±",
  Callback = function()
    loadstring(game:HttpGet("https://pastebin.com/raw/arzRCgwS"))()
  end
})

Tab:AddButton({
  Name = "å…‰å½±_2",
  Default = false,
  Callback = function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/MZEEN2424/Graphics/main/Graphics.xml"))()
  end
})

Tab:AddButton({
	Name = "è¶…é«˜ç”»è´¨",
	Callback = function()
loadstring(game:HttpGet("https://pastebin.com/raw/jHBfJYmS"))()
end
})    

Tab:AddButton({
  Name = "æ—‹è½¬",
  Callback = function()
    loadstring(game:HttpGet('https://pastebin.com/raw/r97d7dS0', true))()
  end
})

Tab:AddButton({
	Name = "è½¬èµ·æ¥",
	Callback = function()
      	loadstring(game:HttpGet('https://pastebin.com/raw/r97d7dS0', true))()
  	end
})

Tab:AddToggle({
	Name = "å¤œè§†",
	Default = false,
	Callback = function(Value)
		if Value then
		    game.Lighting.Ambient = Color3.new(1, 1, 1)
		else
		    game.Lighting.Ambient = Color3.new(0, 0, 0)
		end
	end
})

Tab:AddButton({
	Name = "é£è½¦",
	Callback = function()
loadstring(game:HttpGet("https://pastebin.com/raw/MHE1cbWF"))()
	end
})

Tab:AddButton({
	Name = "çˆ¬å¢™",
	Callback = function()
loadstring(game:HttpGet("https://pastebin.com/raw/zXk4Rq2r"))()
end
})

Tab:AddButton({
    Name = "åŠ¨ä½œ",
    Callback = function()
    loadstring(game:HttpGet("https://pastebin.com/raw/Zj4NnKs6"))()
    end
})

Tab:AddButton({
	Name = "ç”µè„‘é”®ç›˜",
	Callback = function()
     loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))()
  	end    
})

Tab:AddButton({
	Name = "è¸ç©ºè¡Œèµ°",
	Callback = function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/GhostPlayer352/Test4/main/Float'))()
	end
})

local Tab= Window:MakeTab({
	Name = "ğŸ‘ç©å®¶ğŸ‘",
	Icon = "rbxassetid://93566402708060",
	PremiumOnly = false
})

Tab:AddButton({
  Name = "å¥–åŠ±è‡ªå·±",
  Callback = function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/minecrafttotem/yzhs./main/Fe%20pp%20script%20very%20fun"))()
  end
})

Tab:AddButton({
	Name = "æ— é™è·³",
    Default = false,
	Callback = function(Value)
loadstring(game:HttpGet("https://pastebin.com/raw/V5PQy3y0", true))()
	end
})

Tab:AddTextbox({
	Name = "è·³è·ƒé«˜åº¦è®¾ç½®",
	Default = "",
	TextDisappear = true,
	Callback = function(Value)
		game.Players.LocalPlayer.Character.Humanoid.JumpPower = Value
	end
})

Tab:AddTextbox({
åç§°="ç§»åŠ¨é€Ÿåº¦è®¾ç½®",
é»˜è®¤å€¼="",
TextDisappear = true,
å›è°ƒ=å‡½æ•°(å€¼)
æ¸¸æˆã€‚players . local player . character . humanoid . walk speed = Value
ç»“æŸ
})

Tab:AddTextbox({
åç§°="é‡åŠ›è®¾ç½®",
é»˜è®¤å€¼="",
TextDisappear = true,
å›è°ƒ=å‡½æ•°(å€¼)
æ¸¸æˆã€‚å·¥ä½œç©ºé—´ã€‚é‡åŠ›=å€¼
ç»“æŸ
})

Tab:AddToggle({
	Name = "ç©¿å¢™",
é»˜è®¤å€¼=å‡,
å›è°ƒ=å‡½æ•°(å€¼)
å¦‚æœå€¼åˆ™
Noclip = true
		    Stepped = game.RunService.Stepped:Connect(function()
å¦‚æœNoclip == trueï¼Œåˆ™
å¯¹äºä¸€ä¸ª,bæˆå¯¹(æ¸¸æˆã€‚Workspace:GetChildren()) do
å¦‚æœb.Name == gameã€‚ç©å®¶.æœ¬åœ°ç©å®¶.åå­—
å› ä¸ºæˆ‘,væˆå¯¹(æ¸¸æˆã€‚å·¥ä½œç©ºé—´[æ¸¸æˆã€‚ç©å®¶.æœ¬åœ°ç©å®¶.å§“å]:GetChildren()) do
å¦‚æœv:IsA("åŸºç¡€é›¶ä»¶")ç„¶åå‘¢
åŠ¨è¯ ï¼ˆverbçš„ç¼©å†™ï¼‰CanCollide = false
ç»“æŸ
ç»“æŸ
ç»“æŸ
ç»“æŸ
å…¶ä»–
æ­¥è¿›å¼:æ–­å¼€()
ç»“æŸ
		    end)
	    else
Noclip = false
ç»“æŸ
ç»“æŸ
})
